### PR TITLE
Changed naming format

### PR DESCRIPTION
**Pull request by ghost**
Changed naming format from {networkName}IP-{version} to {networkName}IP-{proposalName}-{version}.

Changed the proposal name example from "Byzantium Upgrades on block 123123" to "Byzantium" just to make it shorter as an example.

Corrected some spelling.

### CODE REVIEW

**Comment by phyro** [comment]
@DonaldMcIntyre I think this PR is meant to resolve https://github.com/BelfordZ/starIPs/issues/6 right?

**Comment by ghost** [comment]
That's correct, thank you for the reminder.

**Comment by BelfordZ** [comment]
Thank you for the pull request @DonaldMcIntyre

**Review by BelfordZ — APPROVED** [review]

**Comment by shanejonas** [comment]
👍 

Thank you for your time and this contribution!

**Review by shanejonas — APPROVED** [review]

**Pull request merged**
